import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "GloBus",
    description: "Generated by GloBus Team",
};

export default function RootLayout({ children }) {
    return (
        <html
            foxified=""
            webcrx=""
        >
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased w-[1440px] mx-auto`}
            >
                {children}
            </body>
        </html>
    );
}
