import Header from "@/Components/Header";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "GloBus",
    description: "Generated by GloBus Team",
};

export default function AuthLayout({ children }) {
    return (

        <section
            className="w-[100vw]"
        >
            <Header />
            {children}
        </section>

    );
}
